# Generated by Django 3.2.16 on 2023-02-01 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('about', models.TextField(blank=True, default='All about me', max_length=350)),
                ('maker_or_eater', models.CharField(choices=[('Pizza Eater', 'Pizza Eater'), ('Pizza Maker', 'Pizza Maker')], default='Pizza Eater', max_length=15)),
                ('image', models.ImageField(default='../profile-icon_pqik1e.png', upload_to='images/')),
                ('favourite_pizza', models.CharField(blank=True, default='Margherita', max_length=25)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
